initial
lordkroos12/hw-1 pull request #1
Opened 2024-04-22 17:02 UTC by lordkroos12

2024-04-23 12:52 UTC, IgorKheidorov requested changes
Cool in total, fix the comment

2024-04-23 12:52 UTC, IgorKheidorov commented on Program.cs
> +
a can be greater then b, they can be  negative. Please fix. case

2024-04-23 15:25 UTC, lordkroos12 commented
Is it ok?

2024-04-26 12:36 UTC, IgorKheidorov requested changes

2024-04-26 12:36 UTC, IgorKheidorov commented on Program.cs
> +				b = int.Parse(Console.ReadLine());
Negative values are allowed))), why not?

2024-05-04 16:24 UTC, closed without merging