Task2
lordkroos12/hw-1 pull request #2
Opened 2024-04-22 17:03 UTC by lordkroos12

2024-04-23 12:56 UTC, IgorKheidorov requested changes

2024-04-23 12:56 UTC, IgorKheidorov commented on Program.cs
> +			}
Myabe int checkDigit = (11-(total) % 11)%11 ?;

2024-04-23 15:30 UTC, lordkroos12 commented
I think it is good now

2024-04-26 12:36 UTC, IgorKheidorov approved these changes

2024-05-04 16:24 UTC, closed without merging